# Lab 2: Python Basics, NumPy & Pandas

Welcome to Lab 2! This notebook is your starting point for the Python skills you will use throughout this internship: core Python, NumPy (numerical computing), and Pandas (working with real tabular data).

**After this lab you will be able to:**
- Use Python's core data structures and functions comfortably
- Understand and use NumPy arrays, vectorized operations, and broadcasting
- Load, explore, and manipulate data using Pandas

**Instructions:**
- Write your code between the `### YOUR CODE HERE ###` and `### END ###` markers.
- Run each cell with **Shift + Enter**.
- Compare your output with the **Expected Output** shown below each exercise.
- Try to avoid explicit `for`/`while` loops in the NumPy section unless the exercise asks for one — this is where vectorization comes in.

## How to Use This Notebook

This is a Jupyter/Colab-style notebook made up of two types of cells: **markdown cells** (like this one, for explanations) and **code cells** (where you write and run Python). Run a code cell by clicking it and pressing Shift+Enter — the output appears directly underneath. Variables defined in one cell are available in every cell after it, as long as that cell has already been run.

Let's begin.

## Part 1 — Python Basics Refresher

### 1.1 Variables & F-Strings

Python does not require you to declare a variable's type — it is inferred automatically. f-strings (`f"..."`) are the cleanest way to build strings that include variable values.

**Exercise:** Create three variables — `student_name` (a string), `week_number` (an int), and `score` (a float) — with values of your choice. Then build a single string called `summary` using an f-string in the form: `"<name> is in week <week_number> with a score of <score>"`.

In [2]:
student_name = "Bilawal Khan"
week_number = 1
score = 87.5
summary = f"{student_name} is in week {week_number} with {score}."

print(summary)

Bilawal Khan is in week 1 with 87.5.


**Expected Output (example):**
```
Ayesha is in week 1 with a score of 87.5
```

### 1.2 Lists & Comprehensions

A list comprehension builds a new list from an existing one in a single line, and is used constantly in data work instead of longer loops.

**Exercise:** Given the list `daily_visitors` below, use a list comprehension to create `high_traffic_days`, containing only the values greater than 200.

In [3]:
daily_visitors = [180, 220, 95, 310, 150, 275, 400]
high_traffic_days = [v for v in daily_visitors if v > 200]


print(high_traffic_days)

[220, 310, 275, 400]


**Expected Output:**
```
[220, 310, 275, 400]
```

### 1.3 Dictionaries

Dictionaries map keys to values and are the closest Python equivalent to a real-world lookup table or a single row of structured data.

**Exercise:** Create a dictionary called `product` with keys `"name"`, `"price"`, and `"in_stock"`, using values of your choice. Then write a single f-string, `product_summary`, describing the product using all three values.

In [13]:
product = {
    "name": "Wireless Mouse",
    "price": 19.99 ,
    "in_stock": True
}

product_summary = f"{product['name']} is priced at ${product['price']} and is currently {stock_text}"
print(product_summary)

Wireless Mouse is priced at $19.99 and is currently in stock


**Expected Output (example):**
```
Wireless Mouse is priced at $19.99 and is currently in stock.
```

### 1.4 Functions & Conditionals

**Exercise:** Write a function `classify_score(score)` that returns `"Excellent"` if the score is 90 or above, `"Good"` if it is between 70 (inclusive) and 90, and `"Needs Improvement"` otherwise. Test it on three different values.

In [17]:
def classify_score(score):
    if score >= 90:
        return "Excellent"
    elif score >= 70:
        return "Good"
    else:
        return "Needs Improvement"

print(classify_score(95))
print(classify_score(75))
print(classify_score(40))

Excellent
Good
Needs Improvement


**Expected Output:**
```
Excellent
Good
Needs Improvement
```

**What to remember from Part 1:**
- f-strings are the cleanest way to build strings with variable values
- List comprehensions replace many simple loops
- Dictionaries are Python's key-value lookup structure
- Functions with clear return values are easier to test and reuse

Now that the Python refresher is done, let's move to NumPy — the library almost every data and ML tool in Python is built on top of.

## Part 2 — NumPy Essentials

NumPy's core object is the **array**. Unlike a plain Python list, arrays support **vectorized operations** — applying a computation to every element at once, without writing a loop — which makes them both faster and easier to read.

### 2.1 Creating Arrays

In [18]:
import numpy as np

# Example: converting a list to a NumPy array
temperatures = [22, 25, 19, 30, 28]
temp_array = np.array(temperatures)

print(temp_array)
print(temp_array.shape)
print(temp_array.dtype)

[22 25 19 30 28]
(5,)
int64


### 2.2 Vectorized Operations

**Exercise:** Given the array `prices` below, create `discounted_prices`, where every value has a 15% discount applied — without using a loop.

In [19]:
prices = np.array([1200, 850, 430, 999, 75])
discounted_prices = None

### YOUR CODE HERE ###
discounted_prices = prices * 0.85
### END ###

print(discounted_prices)

[1020.    722.5   365.5   849.15   63.75]


**Expected Output:**
```
[1020.   722.5  365.5  849.15  63.75]
```

### 2.3 Min-Max Normalization

A common preprocessing step in ML is scaling values into a fixed range, typically [0, 1]. The formula for min-max normalization is:

$$ x_{norm} = \frac{x - min(x)}{max(x) - min(x)} $$

**Exercise:** Implement `normalize(x)`, which takes a NumPy array and returns it min-max normalized. Use `np.min()` and `np.max()` — no loops.

In [21]:
def normalize(x):
    ### YOUR CODE HERE ###
    return (np.array(x) - np.min(x)) / (np.max(x) - np.min(x))
    ### END ###
    pass

test_scores = np.array([40, 55, 70, 85, 100])
print(normalize(test_scores))

[0.   0.25 0.5  0.75 1.  ]


**Expected Output:**
```
[0.   0.25 0.5  0.75 1.  ]
```

### 2.4 Reshaping Arrays

`array.shape` tells you an array's dimensions, and `array.reshape(...)` lets you rearrange it into a different shape (as long as the total number of elements matches).

**Exercise:** Given the flat array `readings` (12 sensor readings), reshape it into a 3x4 matrix called `readings_matrix`, then compute the mean of each row using `axis=1`.

In [22]:
readings = np.array([12, 15, 14, 18, 20, 19, 17, 16, 22, 21, 20, 19])
readings_matrix = None
row_means = None

### YOUR CODE HERE ###
readings_matrix = readings.reshape(3, 4)
row_means = np.mean(readings_matrix, axis=1)
### END ###

print(readings_matrix)
print(row_means)

[[12 15 14 18]
 [20 19 17 16]
 [22 21 20 19]]
[14.75 18.   20.5 ]


**Expected Output:**
```
[[12 15 14 18]
 [20 19 17 16]
 [22 21 20 19]]
[14.75 18.   20.5 ]
```

### 2.5 Broadcasting

Broadcasting lets NumPy apply an operation between arrays of different shapes without manually looping — for example, subtracting a single row of column-averages from every row of a matrix.

**Exercise:** Using `readings_matrix` from the previous exercise, subtract the column-wise mean (`axis=0`) from every row, producing `centered_matrix`.

In [23]:
centered_matrix = None

### YOUR CODE HERE ###
centered_matrix = readings_matrix - np.mean(readings_matrix, axis=0)
### END ###

print(centered_matrix)

[[-6.         -3.33333333 -3.          0.33333333]
 [ 2.          0.66666667  0.         -1.66666667]
 [ 4.          2.66666667  3.          1.33333333]]


### 2.6 Why Vectorization Matters

Run the cell below as-is to compare a manual loop against NumPy's vectorized `np.dot()` for computing a dot product on a larger array. Note the difference in computation time.

In [24]:
import time

a = list(range(1_000_000))
b = list(range(1_000_000))

# Manual loop
tic = time.process_time()
loop_dot = 0
for i in range(len(a)):
    loop_dot += a[i] * b[i]
toc = time.process_time()
print("Loop result:", loop_dot, "| Time:", (toc - tic) * 1000, "ms")

# Vectorized with NumPy
a_np = np.array(a)
b_np = np.array(b)

tic = time.process_time()
vec_dot = np.dot(a_np, b_np)
toc = time.process_time()
print("Vectorized result:", vec_dot, "| Time:", (toc - tic) * 1000, "ms")

Loop result: 333332833333500000 | Time: 296.875 ms
Vectorized result: 333332833333500000 | Time: 0.0 ms


**What to remember from Part 2:**
- NumPy arrays support vectorized operations — no loops needed for element-wise math
- `.reshape()` changes an array's dimensions without changing its data
- Broadcasting lets you operate between arrays of different (but compatible) shapes
- Vectorized NumPy code is dramatically faster than an equivalent manual loop

Now let's move to Pandas, which is built on top of NumPy and is the standard tool for working with real, tabular datasets.

## Part 3 — Pandas Essentials

Pandas' main object is the **DataFrame** — a table of rows and columns, similar to a spreadsheet, but fully controllable through code.

### 3.1 Creating and Exploring a DataFrame

In [25]:
import pandas as pd

data = {
    "product": ["Laptop", "Mouse", "Keyboard", "Monitor", "Webcam"],
    "price": [1200, 25, 45, 300, 60],
    "units_sold": [15, 120, 95, 40, 70]
}
df = pd.DataFrame(data)

df.head()

,product,price,units_sold
0,Laptop,1200,15
1,Mouse,25,120
2,Keyboard,45,95
3,Monitor,300,40
4,Webcam,60,70


In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product     5 non-null      str  
 1   price       5 non-null      int64
 2   units_sold  5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 284.0 bytes


In [27]:
df.describe()

,price,units_sold
count,5.000000,5.000000
mean,326.000000,68.000000
std,501.216021,41.922548
min,25.000000,15.000000
25%,45.000000,40.000000
50%,60.000000,70.000000
75%,300.000000,95.000000
max,1200.000000,120.000000


### 3.2 Filtering & Creating New Columns

**Exercise:** Create a new column `revenue` equal to `price * units_sold`. Then create a filtered DataFrame `high_revenue` containing only rows where `revenue` is above 5000.

In [29]:
df["revenue"] = None
high_revenue = None

### YOUR CODE HERE ###
df["revenue"] = df["price"] * df["units_sold"]
high_revenue = df[df["revenue"] > 5000]
### END ###

print(high_revenue)

   product  price  units_sold  revenue
0   Laptop   1200          15    18000
3  Monitor    300          40    12000


### 3.3 Grouping & Aggregating

**Exercise:** Using the `products_extended` DataFrame below (which has a `category` column), compute the average `price` and total `units_sold` per category, in a single `.groupby().agg()` call.

In [32]:
products_extended = pd.DataFrame({
    "product": ["Laptop", "Mouse", "Keyboard", "Monitor", "Webcam", "Desk", "Chair"],
    "category": ["Electronics", "Electronics", "Electronics", "Electronics", "Electronics", "Furniture", "Furniture"],
    "price": [1200, 25, 45, 300, 60, 250, 180],
    "units_sold": [15, 120, 95, 40, 70, 20, 35]
})

category_summary = None

### YOUR CODE HERE ###
category_summary = products_extended.groupby("category").agg({"price": "mean", "units_sold": "sum"})
### END ###

print(category_summary)

             price  units_sold
category                      
Electronics  326.0         340
Furniture    215.0          55


### 3.4 Handling Missing Values

**Exercise:** The DataFrame below has missing values in the `price` column. Create `df_filled`, where missing prices are replaced with the column's average price, using `.fillna()`.

In [39]:
import numpy as np

messy_data = pd.DataFrame({
    "product": ["Tablet", "Charger", "Case", "Earbuds"],
    "price": [400, np.nan, 20, np.nan]
})

df_filled = None

### YOUR CODE HERE ###
df_filled = messy_data.copy()
df_filled["price"] = df_filled["price"].fillna(df_filled["price"].mean())
### END ###

print(df_filled)

   product  price
0   Tablet  400.0
1  Charger  210.0
2     Case   20.0
3  Earbuds  210.0


**What to remember from Part 3:**
- A DataFrame is a table you can filter, transform, and summarize entirely through code
- New columns can be created directly from existing ones
- `.groupby().agg()` is the standard way to summarize data by category
- `.fillna()` is one common way to handle missing values — the right strategy depends on the situation

## Lab Tasks

Complete the following tasks in this notebook, below this cell. These bring together everything covered above.

1. **Personal Data Profile:** Create a dictionary describing yourself (name, role, program week, etc.), then write a function `format_profile(profile_dict)` that returns a formatted, readable summary string built from it.
2. **NumPy Analysis:** Create a NumPy array of at least 10 numbers representing any data of your choice (e.g., daily task counts, temperatures). Compute and print its mean, standard deviation, and the count of values above the mean — without using any loops.
3. **Custom Normalization:** Reuse your `normalize()` function from Part 2 on your own array from Task 2, and print the result.
4. **Mini Dataset Exploration:** Create a small Pandas DataFrame (at least 5 rows, 3 columns) about any topic of your choice. Add one derived column using a calculation on existing columns, then filter the DataFrame based on a condition of your choice.
5. **Summary:** In a markdown cell below your code, write 3-4 sentences in your own words on what you learned in this lab and which part (Python, NumPy, or Pandas) you found most useful or challenging.

In [40]:
# Task 1
# Task 1
# my details in a dictionary
profile = {
    "name": "Bilawal Khan",
    "role": "Data Science student",
    "program_week": 2,
    "goal": "become a data Scientist"
}

# takes the dictionary and builds one readable sentence from it
def format_profile(profile_dict):
    return (f"{profile_dict['name']} is a {profile_dict['role']} in week "
            f"{profile_dict['program_week']} of the program. "
            f"Goal: {profile_dict['goal']}.")

print(format_profile(profile))

Bilawal Khan is a Data Science student in week 2 of the program. Goal: become a data Scientist.


In [41]:
# Task 2
tasks_done = np.array([5, 8, 6, 9, 7, 4, 10, 8, 6, 7, 9, 5])

mean_val = np.mean(tasks_done)
std_val = np.std(tasks_done)

# comparison gives True/False for each day, sum counts the Trues
above_mean = np.sum(tasks_done > mean_val)

print("Mean:", mean_val)
print("Std dev:", std_val)
print("Days above mean:", above_mean)

Mean: 7.0
Std dev: 1.7795130420052185
Days above mean: 5


In [42]:
# Task 3
# using the normalize() function from Part 2 on my array
normalized_tasks = normalize(tasks_done)
print(normalized_tasks)

[0.16666667 0.66666667 0.33333333 0.83333333 0.5        0.
 1.         0.66666667 0.33333333 0.5        0.83333333 0.16666667]


In [43]:
# Task 4
# small stationery shop data
shop = pd.DataFrame({
    "item": ["Notebook", "Pen", "Marker", "Bag", "Calculator"],
    "price": [120, 20, 60, 1500, 900],
    "quantity": [10, 50, 12, 2, 3]
})

# new column: how much money each item brings in
shop["total_cost"] = shop["price"] * shop["quantity"]
print(shop)

# keep only the items with total above 1500
big_items = shop[shop["total_cost"] > 1500]
print(big_items)

         item  price  quantity  total_cost
0    Notebook    120        10        1200
1         Pen     20        50        1000
2      Marker     60        12         720
3         Bag   1500         2        3000
4  Calculator    900         3        2700
         item  price  quantity  total_cost
3         Bag   1500         2        3000
4  Calculator    900         3        2700


_Write your Task 5 summary here._

In this lab I learned how Python, NumPy and Pandas fit together. Python basics like f-strings, dictionaries and functions are the base, NumPy lets me do maths on a whole array at once without loops, and Pandas makes working with table data easy. I found NumPy the most useful because things like normalizing or finding the mean take just one line. The most challenging part for me was groupby and agg in Pandas, since I had to be careful about which function goes with which column.